// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/account-detail-redesign/Consolidated.tsx": () => import("../components/mockups/account-detail-redesign/Consolidated.tsx"),
  "./components/mockups/account-detail-redesign/Current.tsx": () => import("../components/mockups/account-detail-redesign/Current.tsx")
};
