// CRM Association Engine v3
//
// Design principles:
//   1. Manual user decisions always override automation
//   2. Exact known contacts are matched first (Signal 1, +50)
//   3. Account/lead domain matching is second (Signals 2+4, +20/+30)
//   4. Partner matching supported (Signal 5, +35)
//   5. Multiple possible matches create SUGGESTIONS, not automatic guesses (disambiguation)
//   6. Confidence scores + match reasons always stored
//   7. Lead conversion linkage handled externally (see convert route)
//   8. Rejected associations NEVER re-created (feedback table respected)
//
// Writes to:
//   email_associations  — per-message candidate set with scores
//   email_threads       — per-thread primary keys (only when unambiguous + no user override)

import { db } from "../db";
import {
  emailMessages, emailThreads, emailAssociations, associationFeedback,
  contacts, accounts, leads, opportunities, partnerships,
  type EmailMessage,
} from "@shared/schema";
import { eq, and, ilike, inArray, sql } from "drizzle-orm";
import { resolveParticipants, isInternalEmail } from "./identity-resolver";

interface AssocCandidate {
  objectType: "contact" | "account" | "lead" | "opportunity" | "partner";
  objectId: number;
  objectName: string;
  score: number;
  reasons: string[];
  isAmbiguous: boolean;   // true when multiple candidates of same type are close in score
}

// ── Scoring helpers ───────────────────────────────────────────────────────────

function applyPenalties(score: number, msg: EmailMessage, reasons: string[]): number {
  if ((msg.bulkEmailScore ?? 0) >= 40) {
    score -= 60;
    reasons.push(`Bulk email penalty (score ${msg.bulkEmailScore})`);
  }
  if ((msg.autoGeneratedScore ?? 0) >= 40) {
    score -= 50;
    reasons.push(`Auto-generated penalty (score ${msg.autoGeneratedScore})`);
  }
  return score;
}

function applyThreadBonus(score: number, threadRecord: any, reasons: string[]): number {
  if (threadRecord?.associationStatus === "associated") {
    score += 25;
    reasons.push("Thread already CRM-associated");
  }
  return score;
}

function nameInText(name: string, text: string): boolean {
  if (!name || !text || name.length < 4) return false;
  return text.toLowerCase().includes(name.toLowerCase());
}

// ── Disambiguation ────────────────────────────────────────────────────────────
// If 2+ candidates of the same objectType both score >= 30 and their top-gap is
// less than 20 points, none are safe to auto-apply. They become suggestions only.
function applyDisambiguation(candidates: AssocCandidate[]): void {
  const byType = new Map<string, AssocCandidate[]>();
  for (const c of candidates) {
    const group = byType.get(c.objectType) ?? [];
    group.push(c);
    byType.set(c.objectType, group);
  }
  for (const [, group] of byType) {
    if (group.length < 2) continue;
    const sorted = [...group].sort((a, b) => b.score - a.score);
    const top = sorted[0].score;
    const second = sorted[1].score;
    // Ambiguous: both candidates are plausible and close in score
    if (second >= 30 && (top - second) < 20) {
      for (const c of group) {
        c.isAmbiguous = true;
        if (!c.reasons.includes("⚠ Ambiguous — multiple matches, review required")) {
          c.reasons.push("⚠ Ambiguous — multiple matches, review required");
        }
      }
    }
  }
}

// ── Main engine ───────────────────────────────────────────────────────────────

export async function runAssociationEngine(emailMessageId: number): Promise<void> {
  // 1. Load message
  const [msg] = await db
    .select()
    .from(emailMessages)
    .where(eq(emailMessages.id, emailMessageId));
  if (!msg || msg.ignoredReason) return;

  const participants: string[] = JSON.parse(msg.allParticipants || "[]");
  const externalParticipants = participants.filter(e => !isInternalEmail(e));
  if (externalParticipants.length === 0) return;

  // 2. Resolve participants → contacts/accounts/leads
  const resolved = await resolveParticipants(externalParticipants);

  // 3. Load thread record for bonus scoring
  const [threadRecord] = await db
    .select()
    .from(emailThreads)
    .where(eq(emailThreads.gmailThreadId, msg.gmailThreadId))
    .limit(1);

  // 4. Load rejection feedback for all messages in this thread
  //    — ensures rejected associations are NEVER recreated
  const threadMessages = await db
    .select({ id: emailMessages.id })
    .from(emailMessages)
    .where(eq(emailMessages.gmailThreadId, msg.gmailThreadId));
  const threadMsgIds = threadMessages.map(m => m.id);

  const rejectedKeys = new Set<string>();
  if (threadMsgIds.length > 0) {
    const feedback = await db
      .select()
      .from(associationFeedback)
      .where(inArray(associationFeedback.emailMessageId, threadMsgIds));
    feedback
      .filter(f => f.feedbackType === "rejected" && f.originalObjectType && f.originalObjectId)
      .forEach(f => rejectedKeys.add(`${f.originalObjectType}:${f.originalObjectId}`));
  }

  // 5. Load user-confirmed associations for this thread
  //    — these are immutable; engine must not overwrite them
  const confirmedByType = new Map<string, number>(); // objectType → objectId
  if (threadMsgIds.length > 0) {
    const confirmedAssocs = await db
      .select()
      .from(emailAssociations)
      .where(
        and(
          inArray(emailAssociations.emailMessageId, threadMsgIds),
          eq(emailAssociations.isUserConfirmed, true)
        )
      );
    for (const a of confirmedAssocs) {
      // Highest-confidence confirmed association wins for each type
      if (!confirmedByType.has(a.objectType)) {
        confirmedByType.set(a.objectType, a.objectId);
      }
    }
  }

  // ── Domain auto-link rules ────────────────────────────────────────────────
  // Check admin-defined domain rules before running normal scoring signals.
  // Matching rules produce pre-confirmed associations (isUserConfirmed=true)
  // that never appear in the CRM Review queue.
  const earlyDomains = [
    ...new Set(
      externalParticipants
        .map(e => e.split("@")[1]?.toLowerCase())
        .filter((d): d is string => !!d && d.length > 3)
    ),
  ];
  if (earlyDomains.length > 0) {
    try {
      for (const domain of earlyDomains) {
        const ruleRows = await db.execute(
          sql`SELECT * FROM crm_auto_link_rules WHERE domain = ${domain}`
        );
        for (const rule of ruleRows.rows as any[]) {
          if (rejectedKeys.has(`${rule.object_type}:${rule.object_id}`)) continue;
          if (confirmedByType.has(rule.object_type)) continue;
          const [existingAssoc] = await db
            .select({ id: emailAssociations.id })
            .from(emailAssociations)
            .where(and(
              eq(emailAssociations.emailMessageId, emailMessageId),
              eq(emailAssociations.objectType, rule.object_type),
              eq(emailAssociations.objectId, rule.object_id)
            ))
            .limit(1);
          if (!existingAssoc) {
            await db.insert(emailAssociations).values({
              emailMessageId,
              objectType: rule.object_type,
              objectId: rule.object_id,
              objectName: rule.object_name ?? "",
              confidenceScore: 100,
              associationReasonJson: JSON.stringify([
                `Auto-link rule: @${rule.domain} → ${rule.object_name ?? rule.object_type + " #" + rule.object_id}`,
              ]),
              isAuto: false,
              isUserConfirmed: true,
            });
          }
          const threadUpdates: Record<string, any> = { associationStatus: "associated", updatedAt: new Date() };
          if (rule.object_type === "contact") threadUpdates.primaryContactId = rule.object_id;
          else if (rule.object_type === "account") threadUpdates.primaryAccountId = rule.object_id;
          else if (rule.object_type === "lead") threadUpdates.primaryLeadId = rule.object_id;
          else if (rule.object_type === "opportunity") threadUpdates.primaryOpportunityId = rule.object_id;
          else if (rule.object_type === "partner") threadUpdates.primaryPartnerId = rule.object_id;
          if (threadRecord) {
            await db.update(emailThreads).set(threadUpdates).where(eq(emailThreads.gmailThreadId, msg.gmailThreadId));
          } else {
            await db.insert(emailThreads)
              .values({ gmailThreadId: msg.gmailThreadId, ...threadUpdates })
              .onConflictDoUpdate({ target: emailThreads.gmailThreadId, set: threadUpdates });
          }
          confirmedByType.set(rule.object_type, rule.object_id);
        }
      }
    } catch {
      // Table may not exist on first boot before migration completes — fail gracefully
    }
  }

  const normalizedSubject = (msg.normalizedSubject || msg.subject || "").toLowerCase();
  const bodySnippet = (msg.bodyText || "").slice(0, 600).toLowerCase();
  const candidates: AssocCandidate[] = [];

  // Helper to skip rejected candidates early
  function isRejected(type: string, id: number) {
    return rejectedKeys.has(`${type}:${id}`);
  }

  // ── Signal 1: Exact email → Contact (+50) ─────────────────────────────────
  for (const contact of resolved.contacts) {
    if (isRejected("contact", contact.id)) continue;
    const reasons: string[] = [`Exact email match (${contact.email})`];
    let score = 50;
    score = applyThreadBonus(score, threadRecord, reasons);
    if (nameInText(contact.name, normalizedSubject)) {
      score += 15;
      reasons.push("Contact name found in subject");
    }
    score = applyPenalties(score, msg, reasons);
    if (score > 0) {
      candidates.push({ objectType: "contact", objectId: contact.id, objectName: contact.name, score, reasons, isAmbiguous: false });
    }

    // Signal 1a: Account via contact (+35)
    if (!isRejected("account", contact.accountId)) {
      const [acct] = await db
        .select()
        .from(accounts)
        .where(eq(accounts.id, contact.accountId))
        .limit(1);
      if (acct && !candidates.some(c => c.objectType === "account" && c.objectId === acct.id)) {
        const aReasons: string[] = [`Via contact "${contact.name}" (exact email match)`];
        let aScore = 35;
        aScore = applyThreadBonus(aScore, threadRecord, aReasons);
        if (nameInText(acct.name, normalizedSubject) || nameInText(acct.name, bodySnippet)) {
          aScore += 20;
          aReasons.push("Account name in subject/body");
        }
        aScore = applyPenalties(aScore, msg, aReasons);
        if (aScore > 0) {
          candidates.push({ objectType: "account", objectId: acct.id, objectName: acct.name, score: aScore, reasons: aReasons, isAmbiguous: false });
        }
      }
    }

    // Signal 1b: Open opportunity via contact (+20 base, +30 if title in subject)
    // Matches ALL active stages — avoids ne()/not(eq()) Drizzle bug via raw sql
    const openOpps = await db.execute(
      sql`SELECT id, title, account_id, stage FROM opportunities
          WHERE contact_id = ${contact.id}
          AND stage NOT IN ('closed_won', 'closed_lost')`
    );
    for (const opp of openOpps.rows as any[]) {
      if (isRejected("opportunity", opp.id)) continue;
      if (candidates.some(c => c.objectType === "opportunity" && c.objectId === opp.id)) continue;
      const oReasons: string[] = [`Open opportunity via contact "${contact.name}" (${opp.stage} stage)`];
      let oScore = 20;
      if (nameInText(opp.title, normalizedSubject)) {
        oScore += 30;
        oReasons.push("Opportunity title found in email subject");
      }
      oScore = applyPenalties(oScore, msg, oReasons);
      if (oScore >= 40) {
        candidates.push({ objectType: "opportunity", objectId: opp.id, objectName: opp.title, score: oScore, reasons: oReasons, isAmbiguous: false });
      }
    }
  }

  // ── Signal 2: Domain → Account (+20) ─────────────────────────────────────
  for (const account of resolved.accounts) {
    if (isRejected("account", account.id)) continue;
    if (candidates.some(c => c.objectType === "account" && c.objectId === account.id)) continue;
    const reasons: string[] = [`Sender domain @${account.domain} matches account website`];
    let score = 20;
    score = applyThreadBonus(score, threadRecord, reasons);
    if (nameInText(account.name, normalizedSubject) || nameInText(account.name, bodySnippet)) {
      score += 20;
      reasons.push("Account name in subject/body");
    }
    score = applyPenalties(score, msg, reasons);
    if (score > 0) {
      candidates.push({ objectType: "account", objectId: account.id, objectName: account.name, score, reasons, isAmbiguous: false });
    }
  }

  // ── Signal 2b: Open opportunity via account (domain match) (+15) ─────────
  // For every account found via domain, also link open opportunities.
  // Lower base score than contact-routed opps since it's one degree more indirect.
  const accountCandidateIds = candidates
    .filter(c => c.objectType === "account")
    .map(c => c.objectId);
  for (const accountId of accountCandidateIds) {
    const acctOpps = await db.execute(
      sql`SELECT id, title, stage FROM opportunities
          WHERE account_id = ${accountId}
          AND stage NOT IN ('closed_won', 'closed_lost')`
    );
    for (const opp of acctOpps.rows as any[]) {
      if (isRejected("opportunity", opp.id)) continue;
      if (candidates.some(c => c.objectType === "opportunity" && c.objectId === opp.id)) continue;
      const acctName = candidates.find(c => c.objectType === "account" && c.objectId === accountId)?.objectName ?? "";
      const oReasons: string[] = [`Open opportunity via account "${acctName}" (domain match, ${opp.stage} stage)`];
      let oScore = 15;
      if (nameInText(opp.title, normalizedSubject)) {
        oScore += 25;
        oReasons.push("Opportunity title found in email subject");
      }
      oScore = applyPenalties(oScore, msg, oReasons);
      if (oScore >= 30) {
        candidates.push({ objectType: "opportunity", objectId: opp.id, objectName: opp.title, score: oScore, reasons: oReasons, isAmbiguous: false });
      }
    }
  }

  // ── Signal 3: Exact email → Lead (+50) ────────────────────────────────────
  const linkedLeadIds = new Set(resolved.leads.map(l => l.id));
  for (const lead of resolved.leads) {
    if (isRejected("lead", lead.id)) continue;
    const reasons: string[] = [`Exact email match (${lead.email})`];
    let score = 50;
    score = applyThreadBonus(score, threadRecord, reasons);
    if (nameInText(lead.name, normalizedSubject)) {
      score += 10;
      reasons.push("Lead company in subject");
    }
    score = applyPenalties(score, msg, reasons);
    if (score > 0) {
      candidates.push({ objectType: "lead", objectId: lead.id, objectName: lead.name, score, reasons, isAmbiguous: false });
    }
  }

  // ── Signal 4: Domain → Lead (+30) ────────────────────────────────────────
  const participantDomains = [
    ...new Set(
      externalParticipants
        .map(e => e.split("@")[1]?.toLowerCase())
        .filter((d): d is string => !!d && d.length > 3)
    ),
  ];

  for (const domain of participantDomains) {
    const domainLeads = await db
      .select({ id: leads.id, company: leads.company, contactEmail: leads.contactEmail })
      .from(leads)
      .where(ilike(leads.contactEmail, `%@${domain}`));
    for (const lead of domainLeads) {
      if (linkedLeadIds.has(lead.id)) continue;
      if (isRejected("lead", lead.id)) continue;
      linkedLeadIds.add(lead.id);
      const reasons: string[] = [`Lead domain match @${domain} → ${lead.company}`];
      let score = 30;
      score = applyThreadBonus(score, threadRecord, reasons);
      if (nameInText(lead.company, normalizedSubject) || nameInText(lead.company, bodySnippet)) {
        score += 20;
        reasons.push("Lead company name in subject/body");
      }
      score = applyPenalties(score, msg, reasons);
      if (score > 0) {
        candidates.push({ objectType: "lead", objectId: lead.id, objectName: lead.company, score, reasons, isAmbiguous: false });
      }
    }
  }

  // ── Signal 4b: Domain base → Account/Lead name fallback (+18+15=33 max) ────
  // Fires ONLY when the entity name ALSO appears in the email subject or body.
  // This is a hard prerequisite — without content evidence a bare domain-token
  // match is too weak to surface (e.g. @columbia.edu should NOT match every
  // marina prospect named "Columbia X" in the leads database).
  //
  // Both 4b-i and 4b-ii skip the candidate entirely when nameInText() fails.
  // Minimum stored score raised to 25 (18 base + 15 content bonus = 33,
  // then applyPenalties may bring it below 25 for bulk/auto-generated mail).
  for (const domain of participantDomains) {
    const domainBase = domain.split(".")[0];
    if (domainBase.length < 4) continue;

    // 4b-i: account name contains domain base AND appears in email content
    const nameAccounts = await db
      .select({ id: accounts.id, name: accounts.name })
      .from(accounts)
      .where(ilike(accounts.name, `%${domainBase}%`));
    for (const acct of nameAccounts) {
      if (isRejected("account", acct.id)) continue;
      if (candidates.some(c => c.objectType === "account" && c.objectId === acct.id)) continue;
      // Hard prerequisite: name must appear in subject or body snippet
      if (!nameInText(acct.name, normalizedSubject) && !nameInText(acct.name, bodySnippet)) continue;
      const reasons: string[] = [
        `Account name "${acct.name}" contains domain token "${domainBase}" (@${domain})`,
        "Account name confirmed in email subject/body",
      ];
      let score = 33; // 18 base + 15 content-evidence bonus (always granted here)
      score = applyThreadBonus(score, threadRecord, reasons);
      score = applyPenalties(score, msg, reasons);
      if (score >= 25) {
        candidates.push({ objectType: "account", objectId: acct.id, objectName: acct.name, score, reasons, isAmbiguous: false });
      }
    }

    // 4b-ii: lead company name contains domain base AND appears in email content
    const nameLeads = await db
      .select({ id: leads.id, company: leads.company })
      .from(leads)
      .where(ilike(leads.company, `%${domainBase}%`));
    for (const lead of nameLeads) {
      if (linkedLeadIds.has(lead.id)) continue;
      if (isRejected("lead", lead.id)) continue;
      // Hard prerequisite: company name must appear in subject or body snippet
      if (!nameInText(lead.company, normalizedSubject) && !nameInText(lead.company, bodySnippet)) continue;
      linkedLeadIds.add(lead.id);
      const reasons: string[] = [
        `Lead company "${lead.company}" contains domain token "${domainBase}" (@${domain})`,
        "Company name confirmed in email subject/body",
      ];
      let score = 33; // 18 base + 15 content-evidence bonus (always granted here)
      score = applyThreadBonus(score, threadRecord, reasons);
      score = applyPenalties(score, msg, reasons);
      if (score >= 25) {
        candidates.push({ objectType: "lead", objectId: lead.id, objectName: lead.company, score, reasons, isAmbiguous: false });
      }
    }
  }

  // ── Signal 5: Partnership domain match (+35) ─────────────────────────────
  for (const domain of participantDomains) {
    const partnerMatches = await db
      .select({ id: partnerships.id, name: partnerships.name, website: partnerships.website })
      .from(partnerships)
      .where(ilike(partnerships.website, `%${domain}%`));
    for (const partner of partnerMatches) {
      if (isRejected("partner", partner.id)) continue;
      if (candidates.some(c => c.objectType === "partner" && c.objectId === partner.id)) continue;
      const reasons: string[] = [`Partnership domain @${domain} → ${partner.name}`];
      let score = 35;
      score = applyThreadBonus(score, threadRecord, reasons);
      if (nameInText(partner.name, normalizedSubject) || nameInText(partner.name, bodySnippet)) {
        score += 15;
        reasons.push("Partner name in subject/body");
      }
      score = applyPenalties(score, msg, reasons);
      if (score > 0) {
        candidates.push({ objectType: "partner" as any, objectId: partner.id, objectName: partner.name, score, reasons, isAmbiguous: false });
      }
    }
  }

  // ── Signal 6: Lead company name in subject (+25) ─────────────────────────
  // Only triggers when subject has meaningful words AND no lead was already found
  if (normalizedSubject.length >= 5 && candidates.filter(c => c.objectType === "lead").length === 0) {
    const subjectWords = normalizedSubject
      .split(/\W+/)
      .filter(w => w.length >= 5)
      .slice(0, 8);
    for (const word of subjectWords) {
      const subjectLeads = await db
        .select({ id: leads.id, company: leads.company })
        .from(leads)
        .where(ilike(leads.company, `%${word}%`));
      for (const lead of subjectLeads) {
        if (linkedLeadIds.has(lead.id)) continue;
        if (isRejected("lead", lead.id)) continue;
        if (!nameInText(lead.company, normalizedSubject)) continue; // full name must match
        linkedLeadIds.add(lead.id);
        const reasons: string[] = [`Lead company "${lead.company}" found in email subject`];
        let score = 25;
        score = applyPenalties(score, msg, reasons);
        if (score > 0) {
          candidates.push({ objectType: "lead", objectId: lead.id, objectName: lead.company, score, reasons, isAmbiguous: false });
        }
      }
    }
  }

  // ── Disambiguation pass ───────────────────────────────────────────────────
  // If multiple candidates of the same type are close in score, mark them all
  // as suggestions. The engine will not auto-apply ambiguous types to the thread.
  applyDisambiguation(candidates);

  // ── Write email_associations ──────────────────────────────────────────────
  const existing = await db
    .select()
    .from(emailAssociations)
    .where(eq(emailAssociations.emailMessageId, emailMessageId));
  const existingKeys = new Set(existing.map(e => `${e.objectType}:${e.objectId}`));

  for (const cand of candidates) {
    const key = `${cand.objectType}:${cand.objectId}`;
    if (existingKeys.has(key)) continue;
    // isAuto = true only when score is high enough AND unambiguous
    const isAuto = cand.score >= 45 && !cand.isAmbiguous;
    await db.insert(emailAssociations).values({
      emailMessageId,
      objectType: cand.objectType,
      objectId: cand.objectId,
      objectName: cand.objectName,
      confidenceScore: Math.min(100, cand.score),
      associationReasonJson: JSON.stringify(cand.reasons),
      isAuto,
      isUserConfirmed: false,
    });
  }

  // ── Update email_threads primary pointers ─────────────────────────────────
  // Rules:
  //   - Only update a type slot if the user has NOT already confirmed a link for that type
  //   - Only auto-apply if candidate is unambiguous AND above threshold
  //   - Never downgrade a confirmed association
  const best = (type: string) =>
    candidates
      .filter(c => c.objectType === type && !c.isAmbiguous)
      .sort((a, b) => b.score - a.score)[0];

  const topContact = best("contact");
  const topAccount = best("account");
  const topLead = best("lead");
  const topOpp = best("opportunity");
  const topPartner = best("partner");

  const threadData: Record<string, any> = { updatedAt: new Date() };
  let hasNewPrimary = false;

  // Only set if: meets threshold AND no user confirmation already exists for that type
  if (topContact && topContact.score >= 45 && !confirmedByType.has("contact")) {
    threadData.primaryContactId = topContact.objectId;
    hasNewPrimary = true;
  }
  if (topAccount && topAccount.score >= 30 && !confirmedByType.has("account")) {
    threadData.primaryAccountId = topAccount.objectId;
    hasNewPrimary = true;
  }
  if (topLead && topLead.score >= 35 && !confirmedByType.has("lead")) {
    threadData.primaryLeadId = topLead.objectId;
    hasNewPrimary = true;
  }
  if (topOpp && topOpp.score >= 40 && !confirmedByType.has("opportunity")) {
    threadData.primaryOpportunityId = topOpp.objectId;
    hasNewPrimary = true;
  }
  if (topPartner && topPartner.score >= 35 && !confirmedByType.has("partner")) {
    threadData.primaryPartnerId = topPartner.objectId;
    hasNewPrimary = true;
  }

  // Always mark as associated if we have any auto-resolved primary OR any suggestions to review
  const hasCandidates = candidates.length > 0;
  if (hasNewPrimary) threadData.associationStatus = "associated";

  if (hasNewPrimary || hasCandidates) {
    if (threadRecord) {
      await db.update(emailThreads)
        .set(threadData)
        .where(eq(emailThreads.gmailThreadId, msg.gmailThreadId));
    } else {
      await db.insert(emailThreads)
        .values({ gmailThreadId: msg.gmailThreadId, ...threadData })
        .onConflictDoUpdate({
          target: emailThreads.gmailThreadId,
          set: threadData,
        });
    }
  }
}
