// CRM Association Engine v2
// Scores and attaches email threads to CRM entities across 6 signal types.
// Writes to: email_associations (per-message), email_threads (per-thread primary keys)

import { db } from "../db";
import {
  emailMessages, emailThreads, emailAssociations,
  contacts, accounts, leads, opportunities, partnerships,
  type EmailMessage,
} from "@shared/schema";
import { eq, and, ilike } from "drizzle-orm";
import { resolveParticipants, isInternalEmail } from "./identity-resolver";

interface AssocCandidate {
  objectType: "contact" | "account" | "lead" | "opportunity" | "partner";
  objectId: number;
  objectName: string;
  score: number;
  reasons: string[];
}

// Apply bulk/auto-generated penalties
function applyPenalties(score: number, msg: EmailMessage, reasons: string[]): number {
  if ((msg.bulkEmailScore ?? 0) >= 40) {
    score -= 60;
    reasons.push(`Bulk email penalty (score ${msg.bulkEmailScore})`);
  }
  if ((msg.autoGeneratedScore ?? 0) >= 40) {
    score -= 50;
    reasons.push(`Auto-generated penalty (score ${msg.autoGeneratedScore})`);
  }
  return score;
}

// Apply thread history bonus — if thread already has CRM context, boost all candidates
function applyThreadBonus(score: number, threadRecord: any, reasons: string[]): number {
  if (threadRecord?.associationStatus === "associated") {
    score += 25;
    reasons.push("Thread already CRM-associated");
  }
  return score;
}

// Check if a name appears meaningfully in a text block
function nameInText(name: string, text: string): boolean {
  if (!name || !text || name.length < 4) return false;
  return text.toLowerCase().includes(name.toLowerCase());
}

export async function runAssociationEngine(emailMessageId: number): Promise<void> {
  // Load message
  const [msg] = await db.select().from(emailMessages).where(eq(emailMessages.id, emailMessageId));
  if (!msg || msg.ignoredReason) return;

  const participants: string[] = JSON.parse(msg.allParticipants || "[]");
  const externalParticipants = participants.filter(e => !isInternalEmail(e));
  if (externalParticipants.length === 0) return;

  // Resolve via identity-resolver (exact email → contact, domain → account, exact email → lead)
  const resolved = await resolveParticipants(externalParticipants);

  // Load existing thread record for bonus scoring
  const [threadRecord] = await db
    .select()
    .from(emailThreads)
    .where(eq(emailThreads.gmailThreadId, msg.gmailThreadId))
    .limit(1);

  const normalizedSubject = (msg.normalizedSubject || msg.subject || "").toLowerCase();
  const bodySnippet = (msg.bodyText || "").slice(0, 600).toLowerCase();

  const candidates: AssocCandidate[] = [];

  // ── Signal 1: Exact email → Contact (+50) ─────────────────────────────────
  for (const contact of resolved.contacts) {
    const reasons: string[] = [`Exact email match (${contact.email})`];
    let score = 50;
    score = applyThreadBonus(score, threadRecord, reasons);
    if (nameInText(contact.name, normalizedSubject)) {
      score += 15;
      reasons.push("Contact name found in subject");
    }
    score = applyPenalties(score, msg, reasons);
    if (score > 0) {
      candidates.push({ objectType: "contact", objectId: contact.id, objectName: contact.name, score, reasons });
    }

    // Signal 1a: Account via contact (+35)
    const [acct] = await db.select().from(accounts).where(eq(accounts.id, contact.accountId)).limit(1);
    if (acct && !candidates.some(c => c.objectType === "account" && c.objectId === acct.id)) {
      const aReasons: string[] = [`Via contact "${contact.name}"`];
      let aScore = 35;
      aScore = applyThreadBonus(aScore, threadRecord, aReasons);
      if (nameInText(acct.name, normalizedSubject) || nameInText(acct.name, bodySnippet)) {
        aScore += 20;
        aReasons.push("Account name in subject/body");
      }
      aScore = applyPenalties(aScore, msg, aReasons);
      if (aScore > 0) {
        candidates.push({ objectType: "account", objectId: acct.id, objectName: acct.name, score: aScore, reasons: aReasons });
      }
    }

    // Signal 1b: Open opportunity via contact (+20 base, +30 if title in subject)
    const openOpps = await db.select().from(opportunities).where(
      and(eq(opportunities.contactId, contact.id), eq(opportunities.stage, "inbound_new"))
    );
    for (const opp of openOpps) {
      const oReasons: string[] = [`Open opportunity via ${contact.name}`];
      let oScore = 20;
      if (nameInText(opp.title, normalizedSubject)) {
        oScore += 30;
        oReasons.push("Opportunity title in subject");
      }
      oScore = applyPenalties(oScore, msg, oReasons);
      if (oScore >= 40 && !candidates.some(c => c.objectType === "opportunity" && c.objectId === opp.id)) {
        candidates.push({ objectType: "opportunity", objectId: opp.id, objectName: opp.title, score: oScore, reasons: oReasons });
      }
    }
  }

  // ── Signal 2: Domain → Account (+20) ─────────────────────────────────────
  for (const account of resolved.accounts) {
    if (candidates.some(c => c.objectType === "account" && c.objectId === account.id)) continue;
    const reasons: string[] = [`Sender domain @${account.domain} matches account`];
    let score = 20;
    score = applyThreadBonus(score, threadRecord, reasons);
    if (nameInText(account.name, normalizedSubject) || nameInText(account.name, bodySnippet)) {
      score += 20;
      reasons.push("Account name in subject/body");
    }
    score = applyPenalties(score, msg, reasons);
    if (score > 0) {
      candidates.push({ objectType: "account", objectId: account.id, objectName: account.name, score, reasons });
    }
  }

  // ── Signal 3: Exact email → Lead (+50) ────────────────────────────────────
  const linkedLeadIds = new Set(resolved.leads.map(l => l.id));
  for (const lead of resolved.leads) {
    const reasons: string[] = [`Exact email match (${lead.email})`];
    let score = 50;
    score = applyThreadBonus(score, threadRecord, reasons);
    if (nameInText(lead.name, normalizedSubject)) {
      score += 10;
      reasons.push("Lead company in subject");
    }
    score = applyPenalties(score, msg, reasons);
    if (score > 0) {
      candidates.push({ objectType: "lead", objectId: lead.id, objectName: lead.name, score, reasons });
    }
  }

  // ── Signal 4: Domain → Lead (+30, NEW) ───────────────────────────────────
  const participantDomains = [
    ...new Set(
      externalParticipants
        .map(e => e.split("@")[1]?.toLowerCase())
        .filter((d): d is string => !!d && d.length > 3)
    ),
  ];

  for (const domain of participantDomains) {
    const domainLeads = await db
      .select({ id: leads.id, company: leads.company, contactEmail: leads.contactEmail })
      .from(leads)
      .where(ilike(leads.contactEmail, `%@${domain}`));

    for (const lead of domainLeads) {
      if (linkedLeadIds.has(lead.id)) continue;
      linkedLeadIds.add(lead.id);
      const reasons: string[] = [`Lead domain match @${domain} → ${lead.company}`];
      let score = 30;
      score = applyThreadBonus(score, threadRecord, reasons);
      if (nameInText(lead.company, normalizedSubject) || nameInText(lead.company, bodySnippet)) {
        score += 20;
        reasons.push("Lead company name in subject/body");
      }
      score = applyPenalties(score, msg, reasons);
      if (score > 0) {
        candidates.push({ objectType: "lead", objectId: lead.id, objectName: lead.company, score, reasons });
      }
    }
  }

  // ── Signal 5: Partnership domain match (+35, NEW) ─────────────────────────
  for (const domain of participantDomains) {
    const partnerMatches = await db
      .select({ id: partnerships.id, name: partnerships.name, website: partnerships.website })
      .from(partnerships)
      .where(ilike(partnerships.website, `%${domain}%`));

    for (const partner of partnerMatches) {
      if (candidates.some(c => c.objectType === "partner" && c.objectId === partner.id)) continue;
      const reasons: string[] = [`Partnership domain @${domain} → ${partner.name}`];
      let score = 35;
      score = applyThreadBonus(score, threadRecord, reasons);
      if (nameInText(partner.name, normalizedSubject) || nameInText(partner.name, bodySnippet)) {
        score += 15;
        reasons.push("Partner name in subject/body");
      }
      score = applyPenalties(score, msg, reasons);
      if (score > 0) {
        candidates.push({ objectType: "partner" as any, objectId: partner.id, objectName: partner.name, score, reasons });
      }
    }
  }

  // ── Signal 6: Lead company name in subject (+25, NEW) ────────────────────
  // Only runs when there are words >= 5 chars in the subject (avoid false positives)
  if (normalizedSubject.length >= 5 && candidates.filter(c => c.objectType === "lead").length === 0) {
    const subjectWords = normalizedSubject
      .split(/\W+/)
      .filter(w => w.length >= 5)
      .slice(0, 8); // cap to prevent huge queries

    for (const word of subjectWords) {
      const subjectLeads = await db
        .select({ id: leads.id, company: leads.company })
        .from(leads)
        .where(ilike(leads.company, `%${word}%`));

      for (const lead of subjectLeads) {
        if (linkedLeadIds.has(lead.id)) continue;
        if (!nameInText(lead.company, normalizedSubject)) continue; // double-check full name
        linkedLeadIds.add(lead.id);
        const reasons: string[] = [`Lead company "${lead.company}" found in email subject`];
        let score = 25;
        score = applyPenalties(score, msg, reasons);
        if (score > 0) {
          candidates.push({ objectType: "lead", objectId: lead.id, objectName: lead.company, score, reasons });
        }
      }
    }
  }

  // ── Write email_associations ───────────────────────────────────────────────
  const existing = await db
    .select()
    .from(emailAssociations)
    .where(eq(emailAssociations.emailMessageId, emailMessageId));
  const existingKeys = new Set(existing.map(e => `${e.objectType}:${e.objectId}`));

  for (const cand of candidates) {
    const key = `${cand.objectType}:${cand.objectId}`;
    if (existingKeys.has(key)) continue;
    await db.insert(emailAssociations).values({
      emailMessageId,
      objectType: cand.objectType,
      objectId: cand.objectId,
      objectName: cand.objectName,
      confidenceScore: Math.min(100, cand.score),
      associationReasonJson: JSON.stringify(cand.reasons),
      isAuto: cand.score >= 45,
      isUserConfirmed: false,
    });
  }

  // ── Update email_threads primary records ────────────────────────────────────
  const best = (type: string) =>
    candidates.filter(c => c.objectType === type).sort((a, b) => b.score - a.score)[0];

  const topContact = best("contact");
  const topAccount = best("account");
  const topLead = best("lead");
  const topOpp = best("opportunity");
  const topPartner = best("partner");

  const shouldAssociate = !!(
    (topContact && topContact.score >= 45) ||
    (topAccount && topAccount.score >= 30) ||
    (topLead && topLead.score >= 35) ||
    (topOpp && topOpp.score >= 40) ||
    (topPartner && topPartner.score >= 35)
  );

  if (shouldAssociate) {
    const threadData: Record<string, any> = {
      associationStatus: "associated",
      updatedAt: new Date(),
    };
    if (topContact && topContact.score >= 45) threadData.primaryContactId = topContact.objectId;
    if (topAccount && topAccount.score >= 30) threadData.primaryAccountId = topAccount.objectId;
    if (topLead && topLead.score >= 35) threadData.primaryLeadId = topLead.objectId;
    if (topOpp && topOpp.score >= 40) threadData.primaryOpportunityId = topOpp.objectId;
    if (topPartner && topPartner.score >= 35) threadData.primaryPartnerId = topPartner.objectId;

    if (threadRecord) {
      await db.update(emailThreads)
        .set(threadData)
        .where(eq(emailThreads.gmailThreadId, msg.gmailThreadId));
    } else {
      await db.insert(emailThreads)
        .values({ gmailThreadId: msg.gmailThreadId, ...threadData })
        .onConflictDoUpdate({
          target: emailThreads.gmailThreadId,
          set: threadData,
        });
    }
  }
}
