// Auto-Confirmation Sweep — v1 (contact associations only)
//
// Purpose:
//   Sweeps unconfirmed auto-generated contact associations that meet a strict
//   compound gate and marks them as confirmed without human intervention.
//
// isUserConfirmed usage — documented compatibility note:
//   The engine builds a `confirmedByType` map exclusively from `isUserConfirmed=true`
//   records to prevent subsequent messages in the same thread from overwriting the
//   primary pointer. Without this protection, a new inbound message in the same
//   thread would reset `primaryContactId`, destabilising auto-confirmed links.
//   Therefore v1 sets `isUserConfirmed=true`, and treats it as a "resolved/confirmed"
//   flag (human OR auto). The authoritative audit distinction is the feedback record
//   with `feedbackType="auto_confirmed"`. The review queue filter
//   (`isAuto=true AND isUserConfirmed=false`) naturally excludes these records
//   — no query changes are required anywhere.
//
// v1 scope:
//   Only `objectType="contact"` associations. Account, lead, opportunity, and
//   partner auto-confirmation is explicitly excluded pending separate validation.
//
// Compound gate (all conditions must pass):
//   1. confidenceScore >= AUTO_CONFIRM_THRESHOLD (90)
//   2. Reasons JSON contains at least one "Exact email match" signal
//   3. Sender is not a known personal email domain
//   4. Message bulkEmailScore < 40 AND autoGeneratedScore < 40
//   5. No prior "rejected" feedback for this objectType:objectId on this thread
//   6. No prior "auto_confirmed" feedback (idempotency guard)
//
// Dry-run mode:
//   When AUTO_CONFIRM_DRY_RUN=true, the sweep logs every decision but writes
//   nothing to the database. Run in dry-run for at least a week of real traffic
//   before enabling writes.

import { db } from "../db";
import {
  emailAssociations,
  emailMessages,
  emailThreads,
  associationFeedback,
} from "@shared/schema";
import { eq, and, inArray, sql } from "drizzle-orm";

// ── Configuration ─────────────────────────────────────────────────────────────

export const AUTO_CONFIRM_DRY_RUN = true; // ← flip to false to enable writes
const AUTO_CONFIRM_THRESHOLD = 90;
const AUTO_CONFIRM_SCOPE = ["contact"] as const;

const PERSONAL_EMAIL_DOMAINS = new Set([
  "gmail.com", "yahoo.com", "hotmail.com", "outlook.com",
  "live.com", "icloud.com", "protonmail.com", "me.com",
  "aol.com", "msn.com", "ymail.com", "googlemail.com",
]);

// ── Signal helpers ────────────────────────────────────────────────────────────

function hasExactEmailSignal(reasonJson: string | null): boolean {
  if (!reasonJson) return false;
  try {
    const reasons: string[] = JSON.parse(reasonJson);
    return reasons.some(r => r.startsWith("Exact email match"));
  } catch {
    return false;
  }
}

function isPersonalDomain(fromEmail: string | null | undefined): boolean {
  if (!fromEmail) return false;
  const domain = fromEmail.split("@")[1]?.toLowerCase();
  return !!domain && PERSONAL_EMAIL_DOMAINS.has(domain);
}

// ── Sweep ─────────────────────────────────────────────────────────────────────

export async function runAutoConfirmSweep(): Promise<void> {
  const tag = AUTO_CONFIRM_DRY_RUN ? "[auto-confirm dry-run]" : "[auto-confirm]";
  const startedAt = Date.now();

  try {
    // ── Step 1: Load all candidates — unconfirmed, auto, contact, high score ──
    const candidates = await db
      .select({
        assocId: emailAssociations.id,
        emailMessageId: emailAssociations.emailMessageId,
        objectType: emailAssociations.objectType,
        objectId: emailAssociations.objectId,
        objectName: emailAssociations.objectName,
        confidenceScore: emailAssociations.confidenceScore,
        associationReasonJson: emailAssociations.associationReasonJson,
        fromEmail: emailMessages.fromEmail,
        bulkEmailScore: emailMessages.bulkEmailScore,
        autoGeneratedScore: emailMessages.autoGeneratedScore,
        gmailThreadId: emailMessages.gmailThreadId,
      })
      .from(emailAssociations)
      .innerJoin(emailMessages, eq(emailMessages.id, emailAssociations.emailMessageId))
      .where(
        and(
          eq(emailAssociations.isAuto, true),
          eq(emailAssociations.isUserConfirmed, false),
          inArray(emailAssociations.objectType, [...AUTO_CONFIRM_SCOPE]),
          sql`${emailAssociations.confidenceScore} >= ${AUTO_CONFIRM_THRESHOLD}`
        )
      );

    if (candidates.length === 0) {
      console.log(`${tag} No high-confidence contact candidates found — nothing to do`);
      return;
    }

    console.log(`${tag} Evaluating ${candidates.length} candidate(s) (threshold=${AUTO_CONFIRM_THRESHOLD}, scope=${AUTO_CONFIRM_SCOPE.join(",")})`);

    let confirmed = 0;
    let skipped = 0;

    for (const cand of candidates) {
      const label = `assoc#${cand.assocId} contact:${cand.objectId} "${cand.objectName ?? "?"}" score=${cand.confidenceScore}`;

      // ── Gate 1: exact email signal required ────────────────────────────────
      if (!hasExactEmailSignal(cand.associationReasonJson)) {
        console.log(`${tag} SKIP ${label} — no exact email signal in reasons`);
        skipped++;
        continue;
      }

      // ── Gate 2: personal sender domain ────────────────────────────────────
      if (isPersonalDomain(cand.fromEmail)) {
        console.log(`${tag} SKIP ${label} — personal email domain (${cand.fromEmail})`);
        skipped++;
        continue;
      }

      // ── Gate 3: message cleanliness ────────────────────────────────────────
      if ((cand.bulkEmailScore ?? 0) >= 40 || (cand.autoGeneratedScore ?? 0) >= 40) {
        console.log(`${tag} SKIP ${label} — bulk/auto-generated message (bulk=${cand.bulkEmailScore} auto=${cand.autoGeneratedScore})`);
        skipped++;
        continue;
      }

      // ── Gate 4: no prior rejection or auto-confirm feedback on this thread ─
      const threadMessages = await db
        .select({ id: emailMessages.id })
        .from(emailMessages)
        .where(eq(emailMessages.gmailThreadId, cand.gmailThreadId ?? ""));

      const threadMsgIds = threadMessages.map(m => m.id);

      const existingFeedback = threadMsgIds.length > 0
        ? await db
            .select({ feedbackType: associationFeedback.feedbackType })
            .from(associationFeedback)
            .where(
              and(
                inArray(associationFeedback.emailMessageId, threadMsgIds),
                eq(associationFeedback.originalObjectType, cand.objectType),
                eq(associationFeedback.originalObjectId, cand.objectId)
              )
            )
        : [];

      if (existingFeedback.some(f => f.feedbackType === "rejected")) {
        console.log(`${tag} SKIP ${label} — prior rejection feedback exists for this contact on this thread`);
        skipped++;
        continue;
      }

      if (existingFeedback.some(f => f.feedbackType === "auto_confirmed")) {
        console.log(`${tag} SKIP ${label} — already auto-confirmed (idempotency)`);
        skipped++;
        continue;
      }

      // ── All gates pass ─────────────────────────────────────────────────────
      console.log(`${tag} CONFIRM ${label} — all gates pass`);

      if (!AUTO_CONFIRM_DRY_RUN) {
        // Mark as resolved.
        // isUserConfirmed=true is required for engine compatibility: the engine's
        // confirmedByType map uses isUserConfirmed=true to prevent new messages in
        // the same thread from overwriting primaryContactId. See file header for details.
        // isAuto=true is preserved to indicate machine origin.
        // The feedbackType="auto_confirmed" record below is the audit distinction.
        await db
          .update(emailAssociations)
          .set({
            isUserConfirmed: true,
            isAuto: true,          // preserve machine origin
            updatedAt: new Date(),
          })
          .where(eq(emailAssociations.id, cand.assocId));

        // Write audit record — this is what distinguishes auto-confirm from human-confirm.
        await db.insert(associationFeedback).values({
          emailMessageId: cand.emailMessageId,
          originalObjectType: cand.objectType,
          originalObjectId: cand.objectId,
          feedbackType: "auto_confirmed",
        });

        // Update email_threads primary pointer (same logic as single confirm endpoint)
        const [existingThread] = await db
          .select({ id: emailThreads.id })
          .from(emailThreads)
          .where(eq(emailThreads.gmailThreadId, cand.gmailThreadId ?? ""));

        const threadUpdates: Record<string, any> = {
          primaryContactId: cand.objectId,
          associationStatus: "associated",
          updatedAt: new Date(),
        };

        if (existingThread) {
          await db
            .update(emailThreads)
            .set(threadUpdates)
            .where(eq(emailThreads.gmailThreadId, cand.gmailThreadId ?? ""));
        } else if (cand.gmailThreadId) {
          await db
            .insert(emailThreads)
            .values({ gmailThreadId: cand.gmailThreadId, ...threadUpdates });
        }
      }

      confirmed++;
    }

    const elapsed = Date.now() - startedAt;
    console.log(
      `${tag} Complete — ${confirmed} confirmed, ${skipped} skipped ` +
      `(of ${candidates.length} candidates, ${elapsed}ms elapsed)`
    );
  } catch (err: any) {
    console.error(`[auto-confirm] Sweep error: ${err.message}`);
  }
}
