// Auto-Confirmation Sweep — v1 (contact associations only)
//
// Purpose:
//   Sweeps unconfirmed auto-generated contact associations that meet a strict
//   compound gate and marks them as confirmed without human intervention.
//
// isUserConfirmed usage — documented compatibility note:
//   The engine builds a `confirmedByType` map exclusively from `isUserConfirmed=true`
//   records to prevent subsequent messages in the same thread from overwriting the
//   primary pointer. Without this protection, a new inbound message in the same
//   thread would reset `primaryContactId`, destabilising auto-confirmed links.
//   Therefore v1 sets `isUserConfirmed=true`, and treats it as a "resolved/confirmed"
//   flag (human OR auto). The authoritative audit distinction is the feedback record
//   with `feedbackType="auto_confirmed"`. The review queue filter
//   (`isAuto=true AND isUserConfirmed=false`) naturally excludes these records
//   — no query changes are required anywhere.
//
// v1 scope:
//   Only `objectType="contact"` associations. Account, lead, opportunity, and
//   partner auto-confirmation is explicitly excluded pending separate validation.
//
// Compound gate (all conditions must pass):
//   1. confidenceScore >= AUTO_CONFIRM_THRESHOLD (90)
//   2. Reasons JSON contains at least one "Exact email match" signal
//   3. Sender is not a known personal email domain
//   4. Message bulkEmailScore < 40 AND autoGeneratedScore < 40
//   5. No prior "rejected" feedback for this objectType:objectId on this thread
//   6. No prior "auto_confirmed" feedback (idempotency guard)
//
// Dry-run mode:
//   When AUTO_CONFIRM_DRY_RUN=true, the sweep logs every decision but writes
//   nothing to the database. Run in dry-run for at least a week of real traffic
//   before enabling writes.
//
// To enable writes:
//   1. Change AUTO_CONFIRM_DRY_RUN to false in this file.
//   2. Restart the "Start application" workflow.
//   3. No migration required — no schema changes needed.
//   Rollback: set AUTO_CONFIRM_DRY_RUN back to true and restart.
//   To undo already-written confirmations: run the SQL in the rollback section below.

import { db } from "../db";
import {
  emailAssociations,
  emailMessages,
  emailThreads,
  associationFeedback,
} from "@shared/schema";
import { eq, and, inArray, sql } from "drizzle-orm";

// ── Configuration ─────────────────────────────────────────────────────────────

export const AUTO_CONFIRM_DRY_RUN = true; // ← flip to false to enable writes
const AUTO_CONFIRM_THRESHOLD = 90;
const AUTO_CONFIRM_SCOPE = ["contact"] as const;

const PERSONAL_EMAIL_DOMAINS = new Set([
  "gmail.com", "yahoo.com", "hotmail.com", "outlook.com",
  "live.com", "icloud.com", "protonmail.com", "me.com",
  "aol.com", "msn.com", "ymail.com", "googlemail.com",
]);

// ── Types ─────────────────────────────────────────────────────────────────────

export type SkipReason =
  | "no_exact_email_signal"
  | "personal_domain"
  | "bulk_or_auto_generated"
  | "prior_rejection"
  | "already_auto_confirmed";

export interface SweepCandidate {
  assocId: number;
  contactId: number;
  contactName: string | null;
  fromEmail: string | null;
  confidenceScore: number | null;
  reasons: string[];
  bulkEmailScore: number | null;
  autoGeneratedScore: number | null;
  gmailThreadId: string | null;
  outcome: "would_confirm" | "skip";
  skipReason: SkipReason | null;
}

export interface SweepReport {
  ranAt: string;             // ISO timestamp
  dryRun: boolean;
  threshold: number;
  scope: string[];
  pipelineState: {
    emailMessages: number;
    emailAssociations: number;
    associationFeedback: number;
    pipelineReady: boolean;
    note?: string;
  };
  summary: {
    totalCandidates: number;
    wouldConfirm: number;
    skipped: number;
    skipBreakdown: Record<SkipReason, number>;
    elapsedMs: number;
  };
  candidates: SweepCandidate[];
}

// ── Signal helpers ────────────────────────────────────────────────────────────

function parseReasons(reasonJson: string | null): string[] {
  if (!reasonJson) return [];
  try { return JSON.parse(reasonJson); } catch { return []; }
}

function hasExactEmailSignal(reasons: string[]): boolean {
  return reasons.some(r => r.startsWith("Exact email match"));
}

function isPersonalDomain(fromEmail: string | null | undefined): boolean {
  if (!fromEmail) return false;
  const domain = fromEmail.split("@")[1]?.toLowerCase();
  return !!domain && PERSONAL_EMAIL_DOMAINS.has(domain);
}

// ── Core sweep logic (shared by scheduler and report endpoint) ─────────────

export async function buildSweepReport(forceWrite = false): Promise<SweepReport> {
  const startedAt = Date.now();
  const isDryRun = !forceWrite && AUTO_CONFIRM_DRY_RUN;

  // Pipeline state diagnostic
  const [msgResult, assocResult, fbResult] = await Promise.all([
    db.execute(sql`SELECT COUNT(*)::int AS count FROM email_messages`),
    db.execute(sql`SELECT COUNT(*)::int AS count FROM email_associations`),
    db.execute(sql`SELECT COUNT(*)::int AS count FROM association_feedback`),
  ]);

  const msgTotal = Number((msgResult.rows[0] as any)?.count ?? 0);
  const assocTotal = Number((assocResult.rows[0] as any)?.count ?? 0);
  const fbTotal = Number((fbResult.rows[0] as any)?.count ?? 0);
  const pipelineReady = assocTotal > 0;

  const skipBreakdown: Record<SkipReason, number> = {
    no_exact_email_signal: 0,
    personal_domain: 0,
    bulk_or_auto_generated: 0,
    prior_rejection: 0,
    already_auto_confirmed: 0,
  };

  const candidates: SweepCandidate[] = [];

  // Load raw candidates
  const rows = await db
    .select({
      assocId: emailAssociations.id,
      emailMessageId: emailAssociations.emailMessageId,
      objectType: emailAssociations.objectType,
      objectId: emailAssociations.objectId,
      objectName: emailAssociations.objectName,
      confidenceScore: emailAssociations.confidenceScore,
      associationReasonJson: emailAssociations.associationReasonJson,
      fromEmail: emailMessages.fromEmail,
      bulkEmailScore: emailMessages.bulkEmailScore,
      autoGeneratedScore: emailMessages.autoGeneratedScore,
      gmailThreadId: emailMessages.gmailThreadId,
    })
    .from(emailAssociations)
    .innerJoin(emailMessages, eq(emailMessages.id, emailAssociations.emailMessageId))
    .where(
      and(
        eq(emailAssociations.isAuto, true),
        eq(emailAssociations.isUserConfirmed, false),
        inArray(emailAssociations.objectType, [...AUTO_CONFIRM_SCOPE]),
        sql`${emailAssociations.confidenceScore} >= ${AUTO_CONFIRM_THRESHOLD}`
      )
    );

  for (const row of rows) {
    const reasons = parseReasons(row.associationReasonJson);

    // Gate 1
    if (!hasExactEmailSignal(reasons)) {
      skipBreakdown.no_exact_email_signal++;
      candidates.push({
        assocId: row.assocId,
        contactId: row.objectId,
        contactName: row.objectName,
        fromEmail: row.fromEmail,
        confidenceScore: row.confidenceScore,
        reasons,
        bulkEmailScore: row.bulkEmailScore,
        autoGeneratedScore: row.autoGeneratedScore,
        gmailThreadId: row.gmailThreadId,
        outcome: "skip",
        skipReason: "no_exact_email_signal",
      });
      continue;
    }

    // Gate 2
    if (isPersonalDomain(row.fromEmail)) {
      skipBreakdown.personal_domain++;
      candidates.push({
        assocId: row.assocId,
        contactId: row.objectId,
        contactName: row.objectName,
        fromEmail: row.fromEmail,
        confidenceScore: row.confidenceScore,
        reasons,
        bulkEmailScore: row.bulkEmailScore,
        autoGeneratedScore: row.autoGeneratedScore,
        gmailThreadId: row.gmailThreadId,
        outcome: "skip",
        skipReason: "personal_domain",
      });
      continue;
    }

    // Gate 3
    if ((row.bulkEmailScore ?? 0) >= 40 || (row.autoGeneratedScore ?? 0) >= 40) {
      skipBreakdown.bulk_or_auto_generated++;
      candidates.push({
        assocId: row.assocId,
        contactId: row.objectId,
        contactName: row.objectName,
        fromEmail: row.fromEmail,
        confidenceScore: row.confidenceScore,
        reasons,
        bulkEmailScore: row.bulkEmailScore,
        autoGeneratedScore: row.autoGeneratedScore,
        gmailThreadId: row.gmailThreadId,
        outcome: "skip",
        skipReason: "bulk_or_auto_generated",
      });
      continue;
    }

    // Gate 4 — feedback on thread
    const threadMsgs = await db
      .select({ id: emailMessages.id })
      .from(emailMessages)
      .where(eq(emailMessages.gmailThreadId, row.gmailThreadId ?? ""));

    const threadMsgIds = threadMsgs.map(m => m.id);

    const existingFeedback = threadMsgIds.length > 0
      ? await db
          .select({ feedbackType: associationFeedback.feedbackType })
          .from(associationFeedback)
          .where(
            and(
              inArray(associationFeedback.emailMessageId, threadMsgIds),
              eq(associationFeedback.originalObjectType, row.objectType),
              eq(associationFeedback.originalObjectId, row.objectId)
            )
          )
      : [];

    if (existingFeedback.some(f => f.feedbackType === "rejected")) {
      skipBreakdown.prior_rejection++;
      candidates.push({
        assocId: row.assocId,
        contactId: row.objectId,
        contactName: row.objectName,
        fromEmail: row.fromEmail,
        confidenceScore: row.confidenceScore,
        reasons,
        bulkEmailScore: row.bulkEmailScore,
        autoGeneratedScore: row.autoGeneratedScore,
        gmailThreadId: row.gmailThreadId,
        outcome: "skip",
        skipReason: "prior_rejection",
      });
      continue;
    }

    if (existingFeedback.some(f => f.feedbackType === "auto_confirmed")) {
      skipBreakdown.already_auto_confirmed++;
      candidates.push({
        assocId: row.assocId,
        contactId: row.objectId,
        contactName: row.objectName,
        fromEmail: row.fromEmail,
        confidenceScore: row.confidenceScore,
        reasons,
        bulkEmailScore: row.bulkEmailScore,
        autoGeneratedScore: row.autoGeneratedScore,
        gmailThreadId: row.gmailThreadId,
        outcome: "skip",
        skipReason: "already_auto_confirmed",
      });
      continue;
    }

    // All gates pass
    candidates.push({
      assocId: row.assocId,
      contactId: row.objectId,
      contactName: row.objectName,
      fromEmail: row.fromEmail,
      confidenceScore: row.confidenceScore,
      reasons,
      bulkEmailScore: row.bulkEmailScore,
      autoGeneratedScore: row.autoGeneratedScore,
      gmailThreadId: row.gmailThreadId,
      outcome: "would_confirm",
      skipReason: null,
    });

    // Write path (only when explicitly not dry-run)
    if (!isDryRun) {
      await db
        .update(emailAssociations)
        .set({ isUserConfirmed: true, isAuto: true, updatedAt: new Date() })
        .where(eq(emailAssociations.id, row.assocId));

      await db.insert(associationFeedback).values({
        emailMessageId: row.emailMessageId,
        originalObjectType: row.objectType,
        originalObjectId: row.objectId,
        feedbackType: "auto_confirmed",
      });

      const [existingThread] = await db
        .select({ id: emailThreads.id })
        .from(emailThreads)
        .where(eq(emailThreads.gmailThreadId, row.gmailThreadId ?? ""));

      const threadUpdates: Record<string, any> = {
        primaryContactId: row.objectId,
        associationStatus: "associated",
        updatedAt: new Date(),
      };

      if (existingThread) {
        await db.update(emailThreads).set(threadUpdates)
          .where(eq(emailThreads.gmailThreadId, row.gmailThreadId ?? ""));
      } else if (row.gmailThreadId) {
        await db.insert(emailThreads).values({ gmailThreadId: row.gmailThreadId, ...threadUpdates });
      }
    }
  }

  const wouldConfirm = candidates.filter(c => c.outcome === "would_confirm").length;
  const skipped = candidates.filter(c => c.outcome === "skip").length;
  const elapsed = Date.now() - startedAt;

  return {
    ranAt: new Date().toISOString(),
    dryRun: isDryRun,
    threshold: AUTO_CONFIRM_THRESHOLD,
    scope: [...AUTO_CONFIRM_SCOPE],
    pipelineState: {
      emailMessages: msgTotal,
      emailAssociations: assocTotal,
      associationFeedback: fbTotal,
      pipelineReady,
      note: pipelineReady
        ? undefined
        : "email_associations table is empty — the association engine has not run on any messages yet. " +
          "This is expected when Gmail OAuth is not authorized. Re-authorize Trevor's Gmail account to populate this table.",
    },
    summary: {
      totalCandidates: candidates.length,
      wouldConfirm,
      skipped,
      skipBreakdown,
      elapsedMs: elapsed,
    },
    candidates,
  };
}

// ── Scheduled sweep (called hourly by gmail-sync.ts) ─────────────────────────

export async function runAutoConfirmSweep(): Promise<void> {
  const tag = AUTO_CONFIRM_DRY_RUN ? "[auto-confirm dry-run]" : "[auto-confirm]";
  try {
    const report = await buildSweepReport();
    const s = report.summary;

    if (!report.pipelineState.pipelineReady) {
      console.log(`${tag} Pipeline not ready — email_associations table is empty (${report.pipelineState.emailMessages} messages not yet processed)`);
      return;
    }

    if (s.totalCandidates === 0) {
      console.log(`${tag} No high-confidence contact candidates found — nothing to do`);
      return;
    }

    console.log(`${tag} Evaluated ${s.totalCandidates} candidate(s) — ${s.wouldConfirm} would confirm, ${s.skipped} skipped`);

    for (const cand of report.candidates) {
      const label = `assoc#${cand.assocId} contact:${cand.contactId} "${cand.contactName ?? "?"}" score=${cand.confidenceScore}`;
      if (cand.outcome === "would_confirm") {
        console.log(`${tag} CONFIRM ${label}`);
      } else {
        console.log(`${tag} SKIP ${label} — ${cand.skipReason}`);
      }
    }

    const bd = s.skipBreakdown;
    console.log(
      `${tag} Skip breakdown — no_exact_signal:${bd.no_exact_email_signal} ` +
      `personal_domain:${bd.personal_domain} bulk/auto:${bd.bulk_or_auto_generated} ` +
      `prior_rejection:${bd.prior_rejection} already_confirmed:${bd.already_auto_confirmed}`
    );
    console.log(`${tag} Complete — ${s.elapsedMs}ms`);
  } catch (err: any) {
    console.error(`[auto-confirm] Sweep error: ${err.message}`);
  }
}
