// Parses raw Gmail message data into a normalized email record

const GENERIC_DOMAINS = new Set([
  "gmail.com", "googlemail.com", "outlook.com", "hotmail.com",
  "yahoo.com", "icloud.com", "me.com", "live.com", "msn.com",
  "aol.com", "protonmail.com", "proton.me",
]);

const NO_REPLY_PATTERNS = [
  /no.?reply/i, /do.?not.?reply/i, /noreply/i,
  /donotreply/i, /mailer.daemon/i, /auto.?reply/i,
  /notifications?@/i, /alerts?@/i, /support@/i,
];

const BULK_SUBJECT_PATTERNS = [
  /unsubscribe/i, /newsletter/i, /promotional/i,
  /weekly digest/i, /daily digest/i, /marketing/i,
];

export interface ParsedEmail {
  gmailMessageId: string;
  gmailThreadId: string;
  subject: string | null;
  normalizedSubject: string | null;
  fromEmail: string | null;
  fromName: string | null;
  toEmails: string;
  ccEmails: string;
  allParticipants: string;
  sentAt: Date | null;
  bodyText: string | null;
  bodyHtml: string | null;
  direction: string;
  fromDomain: string | null;
  hasAttachments: boolean;
  isReply: boolean;
  unsubscribeDetected: boolean;
  autoGeneratedScore: number;
  bulkEmailScore: number;
  ignoredReason: string | null;
  labelIds: string;
  snippet: string | null;
}

export function parseEmailAddress(raw: string): { email: string; name: string } {
  if (!raw) return { email: "", name: "" };
  const match = raw.match(/^"?([^"<]*)"?\s*<([^>]+)>$/);
  if (match) return { email: match[2].trim().toLowerCase(), name: match[1].trim() };
  const bare = raw.trim().toLowerCase();
  return { email: bare, name: "" };
}

export function parseEmailList(raw: string): string[] {
  if (!raw) return [];
  return raw.split(/,\s*/).map(s => parseEmailAddress(s).email).filter(Boolean);
}

export function extractDomain(email: string): string | null {
  if (!email) return null;
  const parts = email.split("@");
  return parts.length === 2 ? parts[1].toLowerCase() : null;
}

export function isGenericDomain(domain: string | null): boolean {
  if (!domain) return true;
  return GENERIC_DOMAINS.has(domain.toLowerCase());
}

function normalizeSubject(subject: string | null): string | null {
  if (!subject) return null;
  return subject.replace(/^(Re|Fwd|Fw):\s*/gi, "").trim();
}

function getHeader(headers: { name: string; value: string }[], name: string): string {
  return headers.find(h => h.name.toLowerCase() === name.toLowerCase())?.value || "";
}

function decodeBase64(data: string): string {
  try {
    return Buffer.from(data.replace(/-/g, "+").replace(/_/g, "/"), "base64").toString("utf-8");
  } catch {
    return "";
  }
}

function extractTextBody(payload: any): string {
  if (!payload) return "";
  if (payload.mimeType === "text/plain" && payload.body?.data) {
    return decodeBase64(payload.body.data);
  }
  if (payload.parts) {
    for (const part of payload.parts) {
      const text = extractTextBody(part);
      if (text) return text;
    }
  }
  return "";
}

function extractHtmlBody(payload: any): string {
  if (!payload) return "";
  if (payload.mimeType === "text/html" && payload.body?.data) {
    return decodeBase64(payload.body.data);
  }
  if (payload.parts) {
    for (const part of payload.parts) {
      const html = extractHtmlBody(part);
      if (html) return html;
    }
  }
  return "";
}

export function parseGmailMessage(msg: any, myDomain: string): ParsedEmail {
  const headers: { name: string; value: string }[] = msg.payload?.headers || [];
  const fromRaw = getHeader(headers, "From");
  const toRaw = getHeader(headers, "To");
  const ccRaw = getHeader(headers, "Cc");
  const subject = getHeader(headers, "Subject") || null;
  const dateRaw = getHeader(headers, "Date");
  const inReplyTo = getHeader(headers, "In-Reply-To");
  const listUnsubscribe = getHeader(headers, "List-Unsubscribe");
  const precedence = getHeader(headers, "Precedence");
  const xMailer = getHeader(headers, "X-Mailer");
  const autoSubmitted = getHeader(headers, "Auto-Submitted");

  const { email: fromEmail, name: fromName } = parseEmailAddress(fromRaw);
  const toList = parseEmailList(toRaw);
  const ccList = parseEmailList(ccRaw);
  const allParticipants = Array.from(new Set([fromEmail, ...toList, ...ccList].filter(Boolean)));
  const fromDomain = extractDomain(fromEmail);
  const internalDomain = myDomain.toLowerCase();

  const direction = fromDomain === internalDomain ? "outbound" : "inbound";
  const isReply = !!inReplyTo || /^re:/i.test(subject || "");
  const unsubscribeDetected = !!listUnsubscribe;

  let autoGeneratedScore = 0;
  if (NO_REPLY_PATTERNS.some(p => p.test(fromEmail))) autoGeneratedScore += 60;
  if (autoSubmitted && autoSubmitted !== "no") autoGeneratedScore += 40;
  if (precedence === "bulk" || precedence === "list" || precedence === "junk") autoGeneratedScore += 30;
  if (xMailer && /mailchimp|hubspot|salesforce|constantcontact|sendgrid|mailgun/i.test(xMailer)) autoGeneratedScore += 20;

  let bulkEmailScore = 0;
  if (listUnsubscribe) bulkEmailScore += 40;
  if (precedence === "bulk" || precedence === "list") bulkEmailScore += 30;
  if (toList.length > 5) bulkEmailScore += 20;
  if (BULK_SUBJECT_PATTERNS.some(p => p.test(subject || ""))) bulkEmailScore += 25;

  const allInternal = allParticipants.every(e => e.endsWith(`@${internalDomain}`));

  let ignoredReason: string | null = null;
  if (autoGeneratedScore >= 60) ignoredReason = `Auto-generated email (score: ${autoGeneratedScore})`;
  else if (bulkEmailScore >= 60) ignoredReason = `Bulk/newsletter email (score: ${bulkEmailScore})`;
  else if (allInternal) ignoredReason = "Internal-only email";

  const sentAt = dateRaw ? new Date(dateRaw) : msg.internalDate ? new Date(Number(msg.internalDate)) : null;

  const bodyText = extractTextBody(msg.payload);
  const bodyHtml = extractHtmlBody(msg.payload);

  const hasAttachments = (msg.payload?.parts || []).some(
    (p: any) => p.filename && p.filename.length > 0
  );

  const labelIds: string[] = msg.labelIds || [];

  return {
    gmailMessageId: msg.id,
    gmailThreadId: msg.threadId,
    subject,
    normalizedSubject: normalizeSubject(subject),
    fromEmail: fromEmail || null,
    fromName: fromName || null,
    toEmails: JSON.stringify(toList),
    ccEmails: JSON.stringify(ccList),
    allParticipants: JSON.stringify(allParticipants),
    sentAt,
    bodyText: bodyText.slice(0, 4000) || null,
    bodyHtml: bodyHtml.slice(0, 200000) || null,
    direction,
    fromDomain,
    hasAttachments,
    isReply,
    unsubscribeDetected,
    autoGeneratedScore,
    bulkEmailScore,
    ignoredReason,
    labelIds: JSON.stringify(labelIds),
    snippet: msg.snippet || null,
  };
}
